[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = 'redis-helper'
version = "0.0.1"
requires-python = '>=3.6'
dependencies = [
]

[project.optional-dependencies]
dev = ["redis==4.3.2"]
